// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(areas)/asthenoforo-eukarpia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/asthenoforo-eukarpia">> = Specific
  const handler = {} as typeof import("../../src/app/(areas)/asthenoforo-eukarpia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(areas)/asthenoforo-kalamaria/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/asthenoforo-kalamaria">> = Specific
  const handler = {} as typeof import("../../src/app/(areas)/asthenoforo-kalamaria/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(areas)/asthenoforo-kentro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/asthenoforo-kentro">> = Specific
  const handler = {} as typeof import("../../src/app/(areas)/asthenoforo-kentro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(areas)/asthenoforo-neapoli/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/asthenoforo-neapoli">> = Specific
  const handler = {} as typeof import("../../src/app/(areas)/asthenoforo-neapoli/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(areas)/asthenoforo-pylaia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/asthenoforo-pylaia">> = Specific
  const handler = {} as typeof import("../../src/app/(areas)/asthenoforo-pylaia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(areas)/asthenoforo-toumba/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/asthenoforo-toumba">> = Specific
  const handler = {} as typeof import("../../src/app/(areas)/asthenoforo-toumba/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(pages)/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/(pages)/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(pages)/emergency/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/emergency">> = Specific
  const handler = {} as typeof import("../../src/app/(pages)/emergency/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(pages)/international/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/international">> = Specific
  const handler = {} as typeof import("../../src/app/(pages)/international/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(pages)/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../src/app/(pages)/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(pages)/scheduled/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/scheduled">> = Specific
  const handler = {} as typeof import("../../src/app/(pages)/scheduled/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(pages)/special-needs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/special-needs">> = Specific
  const handler = {} as typeof import("../../src/app/(pages)/special-needs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(pages)/timokatalogos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/timokatalogos">> = Specific
  const handler = {} as typeof import("../../src/app/(pages)/timokatalogos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/booking/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/booking">> = Specific
  const handler = {} as typeof import("../../src/app/api/booking/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../src/app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/emergency-call/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/emergency-call">> = Specific
  const handler = {} as typeof import("../../src/app/api/emergency-call/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
